server:
  port: ${SERVER_PORT:8080}
  address: ${SERVER_ADDRESS:0.0.0.0}
spring:
  application:
    name: naukri-be
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
logging:
  level:
    root: INFO
    com.adi.naukri: DEBUG
